"""
Services and Document Knowledge Base for DocMate AI Backend.
Contains verified procedural data for Tamil Nadu / Indian Government citizen services.
"""

SERVICES_DATA = [
    {
        "id": "birth-certificate",
        "category": "certificates",
        "name_en": "Birth Certificate",
        "name_ta": "பிறப்புச் சான்றிதழ்",
        "desc_en": "Official record of a person's birth issued by Corporation / Municipality / Village Panchayat.",
        "desc_ta": "மாநகராட்சி, நகராட்சி அல்லது கிராம பஞ்சாயத்தால் வழங்கப்படும் அதிகாரப்பூர்வ பிறப்பு பதிவு ஆவணம்.",
        "issuing_authority_en": "Corporation / Municipality / Revenue Dept",
        "issuing_authority_ta": "மாநகராட்சி / நகராட்சி / வருவாய்த்துறை",
        "standard_fee": "₹60 (e-Seva service charge)",
        "processing_days": "7 - 15 Working Days",
        "icon": "baby",
        "official_portal": "https://crstn.org/birth_death_tn/",
        "documents": [
            {
                "id": "doc-bc-1",
                "name_en": "Hospital Birth Discharge Summary / Form 1",
                "name_ta": "மருத்துவமனை பிறப்பு அறிக்கை / படிவம் 1",
                "category": "primary_proof",
                "reason_en": "Proves date, time, sex, and place of child birth as reported by the medical institution.",
                "reason_ta": "மருத்துவமனையில் குழந்தை பிறந்த தேதி, நேரம், பாலினம் மற்றும் இடத்தை நிரூபிக்கிறது.",
                "format": "original_and_copy",
                "format_label_en": "Original + 1 Photocopy",
                "format_label_ta": "அசல் + 1 நகல்",
                "note_en": "Must be signed/stamped by the hospital medical officer with registration number.",
                "note_ta": "மருத்துவ அதிகாரியின் கையொப்பம் மற்றும் முத்திரை இருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-bc-2",
                "name_en": "Parents' Aadhaar Cards",
                "name_ta": "பெற்றோரின் ஆதார் அட்டைகள்",
                "category": "identity_proof",
                "reason_en": "Verifies identity, nationality, and parental relationship of both parents.",
                "reason_ta": "தாய், தந்தை இருவரின் அடையாளம் மற்றும் பெற்றோர் உரிமையை சரிபார்க்கிறது.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Photocopy",
                "format_label_ta": "சுய சான்றொப்பமிட்ட நகல்",
                "note_en": "Carry original Aadhaar cards for spot inspection at the e-Seva or Registrar desk.",
                "note_ta": "சரிபார்ப்பிற்காக அசல் ஆதாரை உடன் எடுத்துச் செல்லவும்.",
                "essential": True,
            },
            {
                "id": "doc-bc-3",
                "name_en": "Parents' Marriage Certificate / Ration Card",
                "name_ta": "பெற்றோர் திருமணச் சான்றிதழ் / குடும்ப அட்டை",
                "category": "relationship_proof",
                "reason_en": "Validates marital status of parents and confirms family household listing.",
                "reason_ta": "பெற்றோரின் திருமண உறுதி மற்றும் குடும்ப சேர்க்கையை உறுதி செய்ய.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy",
                "format_label_ta": "1 நகல்",
                "note_en": "If marriage certificate is unavailable, Smart Ration Card or joint affidavit can be submitted.",
                "note_ta": "திருமணச் சான்றிதழ் இல்லையெனில், ஸ்மார்ட் ரேஷன் கார்டு சமர்ப்பிக்கலாம்.",
                "essential": False,
            },
            {
                "id": "doc-bc-4",
                "name_en": "Address Proof of Parents (Electricity Bill / Gas / Ration)",
                "name_ta": "பெற்றோரின் முகவரி சான்று (மின் கட்டணம் / ரேஷன் அட்டை)",
                "category": "address_proof",
                "reason_en": "Establishes permanent/current residence jurisdiction for certificate delivery.",
                "reason_ta": "சான்றிதழ் வழங்கும் அதிகார வரம்பை உறுதி செய்ய முகவரி சான்று தேவை.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy (Recent)",
                "format_label_ta": "1 நகல் (சமீபத்தியது)",
                "note_en": "Address should match the locality of the registrar office if applying locally.",
                "note_ta": "முகவரி சம்பந்தப்பட்ட எல்லைக்குள் இருத்தல் நலம்.",
                "essential": True,
            },
            {
                "id": "doc-bc-5",
                "name_en": "Delayed Registration Non-Availability Certificate (If > 1 year)",
                "name_ta": "தாமத பதிவுக்கான தடையில்லாச் சான்று (1 வருடத்திற்கு மேல் எனில்)",
                "category": "supporting_proof",
                "reason_en": "Mandatory if birth was not registered within 21 days or 1 year under Section 13(3) of RBD Act.",
                "reason_ta": "குழந்தை பிறந்து 1 வருடத்திற்கு மேல் பதிவு செய்யப்படாமல் இருந்தால் வருவாய் கோட்டாட்சியர் (RDO) உத்தரவு தேவை.",
                "format": "original",
                "format_label_en": "Original Order / Court Order",
                "format_label_ta": "அசல் ஆணை / நீதிமன்ற உத்தரவு",
                "note_en": "Requires an affidavit and order from the Revenue Divisional Officer (RDO) or Magistrate.",
                "note_ta": "RDO அல்லது வட்டாட்சியர் அனுமதியுடன் கூடிய பிரமாணப் பத்திரம் தேவை.",
                "essential": False,
                "conditional": "Only for delayed registration (>1 year)"
            }
        ]
    },
    {
        "id": "community-certificate",
        "category": "certificates",
        "name_en": "Community Certificate (SC / ST / BC / MBC / OBC)",
        "name_ta": "சாதிச் சான்றிதழ் (BC / MBC / SC / ST / OBC)",
        "desc_en": "Certifies reservation category for education, government examinations, and welfare benefits.",
        "desc_ta": "கல்வி, வேலைவாய்ப்பு மற்றும் அரசு நலத்திட்டங்களுக்கான சாதி பிரிவு சான்றளிப்பு ஆவணம்.",
        "issuing_authority_en": "Revenue Dept (Tahsildar / Zonal Deputy Tahsildar)",
        "issuing_authority_ta": "வருவாய்த்துறை (வட்டாட்சியர் / மண்டல துணை வட்டாட்சியர்)",
        "standard_fee": "₹60 (e-Seva charge)",
        "processing_days": "15 - 30 Working Days",
        "icon": "badge",
        "official_portal": "https://www.tnesevai.tn.gov.in/",
        "documents": [
            {
                "id": "doc-cc-1",
                "name_en": "Applicant's School Transfer Certificate (TC) / Marksheet",
                "name_ta": "விண்ணப்பதாரரின் பள்ளி மாற்றுச் சான்றிதழ் (TC) / மதிப்பெண் பட்டியல்",
                "category": "primary_proof",
                "reason_en": "Contains student's community/caste as recorded during school admission.",
                "reason_ta": "பள்ளி சேர்க்கையின் போது பதிவு செய்யப்பட்ட சாதி விபரத்தை நிரூபிக்கிறது.",
                "format": "photocopy_self_attested",
                "format_label_en": "Photocopy with School Stamp",
                "format_label_ta": "பள்ளி முத்திரையுடன் கூடிய நகல்",
                "note_en": "Community column should not be left blank or written as 'Not Disclosed'.",
                "note_ta": "சாதி பத்தி காலியாக இருக்கக்கூடாது.",
                "essential": True,
            },
            {
                "id": "doc-cc-2",
                "name_en": "Father's or Mother's Community Certificate",
                "name_ta": "தந்தை அல்லது தாயின் சாதிச் சான்றிதழ்",
                "category": "relationship_proof",
                "reason_en": "Primary lineage proof to certify community heritage.",
                "reason_ta": "குடும்ப பாரம்பரிய சாதியை நிரூபிக்கும் முதன்மை ஆவணம்.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Photocopy",
                "format_label_ta": "சுய சான்றொப்பமிட்ட நகல்",
                "note_en": "If father's certificate is missing, sibling's or paternal uncle's certificate + notary affidavit is accepted.",
                "note_ta": "தந்தை சான்றிதழ் இல்லையெனில், உடன் பிறந்தோர் அல்லது சித்தப்பா/பெரியப்பா சான்றிதழ் சமர்ப்பிக்கலாம்.",
                "essential": True,
            },
            {
                "id": "doc-cc-3",
                "name_en": "Smart Ration Card / Family Card",
                "name_ta": "ஸ்மார்ட் குடும்ப அட்டை (ரேஷன் கார்டு)",
                "category": "address_proof",
                "reason_en": "Confirms applicant's inclusion in family household and local residency.",
                "reason_ta": "குடும்ப உறுப்பினர்களின் விவரம் மற்றும் வசிப்பிடத்தை உறுதி செய்ய.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy",
                "format_label_ta": "1 நகல்",
                "note_en": "Applicant's name must be listed among the card members.",
                "note_ta": "விண்ணப்பதாரரின் பெயர் அட்டையில் சேர்க்கப்பட்டிருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-cc-4",
                "name_en": "Applicant's Aadhaar Card",
                "name_ta": "விண்ணப்பதாரரின் ஆதார் அட்டை",
                "category": "identity_proof",
                "reason_en": "Unique biometric identity confirmation for CAN registration.",
                "reason_ta": "CAN பதிவுக்கு பயோமெட்ரிக் அடையாள உறுதி.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Copy",
                "format_label_ta": "சுய சான்றொப்பமிட்ட நகல்",
                "note_en": "Mobile number must be linked with Aadhaar for OTP verification.",
                "note_ta": "OTP வர மொபைல் எண் ஆதாருடன் இணைக்கப்பட்டிருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-cc-5",
                "name_en": "Passport Size Photographs (2 Nos)",
                "name_ta": "பாஸ்போர்ட் அளவு புகைப்படங்கள் (2)",
                "category": "photo_proof",
                "reason_en": "For digital photo capture and application file record.",
                "reason_ta": "சான்றிதழில் அச்சிடுவதற்கும் கோப்பு பதிவுக்கும்.",
                "format": "original",
                "format_label_en": "Recent Color Photos",
                "format_label_ta": "சமீபத்திய வண்ணப் படங்கள்",
                "note_en": "Taken against a white or light background within the last 3 months.",
                "note_ta": "வெள்ளை பின்னணியில் 3 மாதங்களுக்குள் எடுக்கப்பட்டது.",
                "essential": True,
            }
        ]
    },
    {
        "id": "income-certificate",
        "category": "certificates",
        "name_en": "Income Certificate",
        "name_ta": "வருமானச் சான்றிதழ்",
        "desc_en": "Official certification of annual household income for scholarships, fee waivers, and government welfare schemes.",
        "desc_ta": "கல்வி உதவித்தொகை மற்றும் அரசு திட்டங்களுக்கு குடும்பத்தின் ஆண்டு வருமானத்தை சான்றளிக்கும் ஆவணம்.",
        "issuing_authority_en": "Revenue Dept (Zonal Deputy Tahsildar)",
        "issuing_authority_ta": "வருவாய்த்துறை (மண்டல துணை வட்டாட்சியர்)",
        "standard_fee": "₹60 (e-Seva charge)",
        "processing_days": "7 - 15 Working Days",
        "icon": "currency",
        "official_portal": "https://www.tnesevai.tn.gov.in/",
        "documents": [
            {
                "id": "doc-ic-1",
                "name_en": "Salary Certificate / Payslip / Form 16 (Salaried)",
                "name_ta": "சம்பளச் சான்றிதழ் / சம்பள ரசீது (மாத சம்பளம் பெறுவோர்)",
                "category": "primary_proof",
                "reason_en": "Verifies documented gross annual income from employer.",
                "reason_ta": "நிறுவனத்தால் வழங்கப்பட்ட ஆண்டு வருமான விபரம்.",
                "format": "original_and_copy",
                "format_label_en": "Original stamped or Form 16",
                "format_label_ta": "முத்திரையுடன் கூடிய அசல் அல்லது Form 16",
                "note_en": "For private/govt employees. Daily wage/self-employed submit VAO certificate or Notary Affidavit.",
                "note_ta": "சுயதொழில் செய்பவர்கள் நோட்டரி உறுதிமொழி பத்திரம் சமர்ப்பிக்கலாம்.",
                "essential": True,
            },
            {
                "id": "doc-ic-2",
                "name_en": "Smart Ration Card / Family Card",
                "name_ta": "ஸ்மார்ட் குடும்ப அட்டை (ரேஷன் கார்டு)",
                "category": "relationship_proof",
                "reason_en": "Determines total number of earning and dependent household members.",
                "reason_ta": "குடும்ப உறுப்பினர்கள் மற்றும் சார்புடையோரின் எண்ணிக்கையை அறிய.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy",
                "format_label_ta": "1 நகல்",
                "note_en": "Ensures all family income streams are accounted for under single roof.",
                "note_ta": "அனைத்து உறுப்பினர்களின் விபரங்களும் உள்ளடங்கியிருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-ic-3",
                "name_en": "Aadhaar Card of Applicant & Family Head",
                "name_ta": "விண்ணப்பதாரர் மற்றும் குடும்பத் தலைவரின் ஆதார்",
                "category": "identity_proof",
                "reason_en": "Identity and biometric deduplication for revenue database.",
                "reason_ta": "அடையாள சரிபார்ப்புக்காக.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Photocopy",
                "format_label_ta": "சுய சான்றொப்பமிட்ட நகல்",
                "note_en": "Ensure name spellings match the family ration card.",
                "note_ta": "குடும்ப அட்டையில் உள்ள பெயருடன் ஒத்துப்போக வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-ic-4",
                "name_en": "Self-Declaration / Notarized Income Affidavit",
                "name_ta": "வருமான சுய அறிவிப்பு / நோட்டரி உறுதிமொழி பத்திரம்",
                "category": "supporting_proof",
                "reason_en": "Legally binding statement of annual income from agriculture, business, or daily wages.",
                "reason_ta": "விவசாயம் அல்லது கூலி வேலை செய்பவர்கள் வருமானத்தை உறுதி செய்ய.",
                "format": "original",
                "format_label_en": "Signed Form / ₹20 Stamp Paper",
                "format_label_ta": "கையொப்பமிட்ட படிவம் / முத்திரைத்தாள்",
                "note_en": "Available at e-Seva desk or sworn before a Notary Public.",
                "note_ta": "இ-சேவை மையத்திலேயே சுய உறுதிமொழி படிவம் பெறலாம்.",
                "essential": True,
            }
        ]
    },
    {
        "id": "residence-certificate",
        "category": "certificates",
        "name_en": "Nativity / Residence Certificate",
        "name_ta": "இருப்பிடச் சான்றிதழ் / பிறப்பிடச் சான்றிதழ்",
        "desc_en": "Certifies continuous residence in a state/district for 5+ years for quota admissions and government jobs.",
        "desc_ta": "கல்வி மற்றும் அரசு பணிகளுக்கான உள்ளூர் இருப்பிடத்தை உறுதி செய்யும் ஆவணம்.",
        "issuing_authority_en": "Revenue Dept (Tahsildar)",
        "issuing_authority_ta": "வருவாய்த்துறை (வட்டாட்சியர்)",
        "standard_fee": "₹60 (e-Seva charge)",
        "processing_days": "7 - 15 Working Days",
        "icon": "home",
        "official_portal": "https://www.tnesevai.tn.gov.in/",
        "documents": [
            {
                "id": "doc-rc-1",
                "name_en": "Smart Ration Card / Family Card",
                "name_ta": "ஸ்மார்ட் குடும்ப அட்டை (ரேஷன் கார்டு)",
                "category": "primary_proof",
                "reason_en": "Proves long-term household residence within the village/taluk jurisdiction.",
                "reason_ta": "பகுதியில் நீண்டகால குடும்ப வசிப்பிடத்தை உறுதி செய்ய.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy",
                "format_label_ta": "1 நகல்",
                "note_en": "Must display the current residential address.",
                "note_ta": "நடப்பு முகவரி குறிப்பிடப்பட்டிருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-rc-2",
                "name_en": "Applicant's School Study Certificate (5+ Years)",
                "name_ta": "பள்ளி படிப்புச் சான்றிதழ் (குறைந்தது 5 ஆண்டுகள்)",
                "category": "primary_proof",
                "reason_en": "Proves continuous education within the state/district.",
                "reason_ta": "இம்மாநிலத்தில் தொடர்ந்து கல்வி பயின்றதை நிரூபிக்கிறது.",
                "format": "original_and_copy",
                "format_label_en": "Bona-fide Study Certificate",
                "format_label_ta": "பள்ளி தலைமை ஆசிரியர் சான்று",
                "note_en": "Signed and stamped by Headmaster or Principal.",
                "note_ta": "தலைமை ஆசிரியர் முத்திரை மற்றும் கையொப்பத்துடன்.",
                "essential": True,
            },
            {
                "id": "doc-rc-3",
                "name_en": "Electricity Bill (EB) / Property Tax Receipt",
                "name_ta": "மின்கட்டண ரசீது / சொத்து வரி ரசீது",
                "category": "address_proof",
                "reason_en": "Validates physical domestic connection at the stated address.",
                "reason_ta": "முகவரியில் குடியிருப்பதற்கான ரசீது.",
                "format": "photocopy",
                "format_label_en": "Recent Bill (<3 Months)",
                "format_label_ta": "சமீபத்திய 3 மாத ரசீது",
                "note_en": "If rented, attach registered rental agreement + owner's EB receipt.",
                "note_ta": "வாடகை வீடு எனில் வாடகை ஒப்பந்தம் மற்றும் உரிமையாளர் மின்கட்டண ரசீது.",
                "essential": True,
            }
        ]
    },
    {
        "id": "first-graduate-certificate",
        "category": "certificates",
        "name_en": "First Graduate Certificate",
        "name_ta": "முதல் பட்டதாரி சான்றிதழ்",
        "desc_en": "Grants government tuition fee concession for students who are the first in their entire family to enter degree college.",
        "desc_ta": "குடும்பத்தில் முதல் பட்டதாரி மாணவருக்கு அரசு கல்விக் கட்டணச் சலுகை வழங்கும் சான்றிதழ்.",
        "issuing_authority_en": "Revenue Dept (Tahsildar / Zonal Deputy Tahsildar)",
        "issuing_authority_ta": "வருவாய்த்துறை (வட்டாட்சியர்)",
        "standard_fee": "₹60 (e-Seva charge)",
        "processing_days": "15 - 30 Working Days",
        "icon": "academic-cap",
        "official_portal": "https://www.tnesevai.tn.gov.in/",
        "documents": [
            {
                "id": "doc-fg-1",
                "name_en": "Parents' & Grandparents' Educational Qualification Certificates / TC",
                "name_ta": "பெற்றோர் மற்றும் தாத்தா/பாட்டியின் கல்வி சான்றிதழ் அல்லது TC",
                "category": "primary_proof",
                "reason_en": "Proves none of the immediate ancestors completed a college degree.",
                "reason_ta": "முந்தைய தலைமுறையினர் பட்டப்படிப்பு முடிக்கவில்லை என்பதை நிரூபிக்க.",
                "format": "photocopy_self_attested",
                "format_label_en": "TC / Marksheet / Non-literate declaration",
                "format_label_ta": "TC அல்லது படிப்பறிவற்றவர் உறுதிமொழி",
                "note_en": "If parents never attended school, notarized non-literate declaration is acceptable.",
                "note_ta": "பள்ளிக்கு செல்லாதவர்கள் எனில் பிரமாண பத்திரம் சமர்ப்பிக்கலாம்.",
                "essential": True,
            },
            {
                "id": "doc-fg-2",
                "name_en": "Siblings' Educational Proof & TC",
                "name_ta": "உடன்பிறந்தோரின் கல்விச் சான்றிதழ் மற்றும் TC",
                "category": "relationship_proof",
                "reason_en": "Ensures no elder brother or sister has already completed or availed first-graduate benefit.",
                "reason_ta": "மூத்த சகோதரர்/சகோதரி யாரும் பட்டப்படிப்பு முடிக்கவில்லை என உறுதி செய்ய.",
                "format": "photocopy",
                "format_label_en": "TC / Bonafide Certificate",
                "format_label_ta": "மாற்றுச் சான்றிதழ்",
                "note_en": "Benefit can only be availed by ONE student in a family.",
                "note_ta": "ஒரு குடும்பத்தில் ஒருவருக்கு மட்டுமே இச்சலுகை கிடைக்கும்.",
                "essential": True,
            },
            {
                "id": "doc-fg-3",
                "name_en": "First Graduate Joint Self-Declaration Form",
                "name_ta": "முதல் பட்டதாரி கூட்டு உறுதிமொழி படிவம்",
                "category": "supporting_proof",
                "reason_en": "Signed joint affidavit by student and parent affirming no graduates exist in household.",
                "reason_ta": "மாணவர் மற்றும் பெற்றோர் கையொப்பமிட்ட உறுதிமொழி படிவம்.",
                "format": "original",
                "format_label_en": "Standard Form Signed by Parent & Student",
                "format_label_ta": "அசல் படிவம்",
                "note_en": "Format can be downloaded directly from e-Seva portal or filled at center.",
                "note_ta": "இ-சேவை மையத்தில் படிவம் கிடைக்கும்.",
                "essential": True,
            }
        ]
    },
    {
        "id": "legal-heir-certificate",
        "category": "certificates",
        "name_en": "Legal Heir Certificate (வாரிசுச் சான்றிதழ்)",
        "name_ta": "வாரிசுச் சான்றிதழ்",
        "desc_en": "Establishes living legal heirs of a deceased person for pension transfer, bank asset release, and property succession.",
        "desc_ta": "மறைந்த நபரின் சட்டப்பூர்வ வாரிசுகளை உறுதிப்படுத்தும் அரசு சான்றிதழ்.",
        "issuing_authority_en": "Revenue Dept (Tahsildar)",
        "issuing_authority_ta": "வருவாய்த்துறை (வட்டாட்சியர்)",
        "standard_fee": "₹60 (e-Seva charge)",
        "processing_days": "15 - 30 Working Days",
        "icon": "users",
        "official_portal": "https://www.tnesevai.tn.gov.in/",
        "documents": [
            {
                "id": "doc-lh-1",
                "name_en": "Original Death Certificate of Deceased",
                "name_ta": "மறைந்தவரின் அசல் இறப்புச் சான்றிதழ்",
                "category": "primary_proof",
                "reason_en": "Foundational proof establishing legal demise.",
                "reason_ta": "மரணத்தை சட்டப்பூர்வமாக நிரூபிக்கும் முதன்மை ஆவணம்.",
                "format": "original_and_copy",
                "format_label_en": "Original + 2 Photocopies",
                "format_label_ta": "அசல் + 2 நகல்கள்",
                "note_en": "Must be issued by Municipality, Corporation, or Taluk registrar.",
                "note_ta": "அரசு பதிவாளரால் வழங்கப்பட்டதாக இருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-lh-2",
                "name_en": "Smart Ration Card of Deceased",
                "name_ta": "மறைந்தவரின் குடும்ப அட்டை (ரேஷன் கார்டு)",
                "category": "relationship_proof",
                "reason_en": "Lists family members residing with deceased at time of demise.",
                "reason_ta": "மறைந்தவருடன் வாழ்ந்த குடும்ப உறுப்பினர்களை சரிபார்க்க.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy",
                "format_label_ta": "1 நகல்",
                "note_en": "Deceased name should be present or updated.",
                "note_ta": "மறைந்தவரின் பெயர் இடம்பெற்றிருக்க வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-lh-3",
                "name_en": "Aadhaar Cards of All Living Legal Heirs",
                "name_ta": "உயிருடன் உள்ள அனைத்து வாரிசுகளின் ஆதார் அட்டைகள்",
                "category": "identity_proof",
                "reason_en": "Identity and biometric record of spouse, sons, daughters, and surviving parents.",
                "reason_ta": "மனைவி, மக்கள், பெற்றோரின் அடையாள உறுதி.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Copies of All Heirs",
                "format_label_ta": "அனைத்து வாரிசுகளின் சுய சான்றொப்பமிட்ட நகல்கள்",
                "note_en": "All living heirs must be included. Hiding an heir is punishable by law.",
                "note_ta": "எந்த ஒரு வாரிசையும் மறைக்கக்கூடாது.",
                "essential": True,
            }
        ]
    },
    {
        "id": "driving-license",
        "category": "licenses",
        "name_en": "Driving License (LLR & Permanent DL)",
        "name_ta": "ஓட்டுநர் உரிமம் (LLR & Permanent DL)",
        "desc_en": "Official permission to operate motor vehicles issued by Regional Transport Office (RTO).",
        "desc_ta": "வாகனங்களை இயக்குவதற்கான அதிகாரப்பூர்வ வட்டாரப் போக்குவரத்து அலுவலக (RTO) உரிமம்.",
        "issuing_authority_en": "Transport Dept (RTO)",
        "issuing_authority_ta": "போக்குவரத்துத்துறை (RTO)",
        "standard_fee": "₹200 - ₹500 (Parivahan online portal fee)",
        "processing_days": "Same Day (LLR) / 15 Days (DL Test)",
        "icon": "truck",
        "official_portal": "https://parivahan.gov.in/",
        "documents": [
            {
                "id": "doc-dl-1",
                "name_en": "Age Proof (10th Marksheet / Birth Certificate / Passport)",
                "name_ta": "வயது சான்று (10-ஆம் வகுப்பு மதிப்பெண் பட்டியல் / பிறப்புச் சான்றிதழ்)",
                "category": "primary_proof",
                "reason_en": "Proves applicant is at least 18 years of age (16 for gearless <50cc).",
                "reason_ta": "18 வயது பூர்த்தியடைந்ததை நிரூபிக்கிறது.",
                "format": "photocopy_self_attested",
                "format_label_en": "Original + 1 Copy",
                "format_label_ta": "அசல் + 1 நகல்",
                "note_en": "Date of Birth must match Aadhaar card exactly.",
                "note_ta": "பிறந்த தேதி ஆதாருடன் சரியாக பொருந்த வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-dl-2",
                "name_en": "Address Proof (Aadhaar / Voter ID / Passport)",
                "name_ta": "முகவரி சான்று (ஆதார் / வாக்காளர் அட்டை / பாஸ்போர்ட்)",
                "category": "address_proof",
                "reason_en": "Establishes RTO jurisdiction for vehicle testing.",
                "reason_ta": "சம்பந்தப்பட்ட RTO அதிகார வரம்பை உறுதி செய்ய.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Copy",
                "format_label_ta": "சுய சான்றொப்பமிட்ட நகல்",
                "note_en": "DigiLocker version also accepted during online Sarathi application.",
                "note_ta": "சாரதி போர்ட்டலில் டிஜிலாக்கர் மூலமும் சரிபார்க்கலாம்.",
                "essential": True,
            },
            {
                "id": "doc-dl-3",
                "name_en": "Form 1 Medical Self-Declaration & Form 1A (if >40 years or transport)",
                "name_ta": "மருத்துவ தகுதி படிவம் (Form 1 / 1A)",
                "category": "supporting_proof",
                "reason_en": "Certifies physical and visual fitness for operating vehicles on public roads.",
                "reason_ta": "வாகனம் ஓட்ட உடல் மற்றும் கண் பார்வை தகுதி சான்று.",
                "format": "original",
                "format_label_en": "Signed Form / Doctor Certified",
                "format_label_ta": "மருத்துவர் சான்றளித்த படிவம்",
                "note_en": "Form 1A must be signed by a registered medical practitioner with seal.",
                "note_ta": "பதிவு பெற்ற மருத்துவர் கையொப்பம் மற்றும் முத்திரை இருக்க வேண்டும்.",
                "essential": True,
            }
        ]
    },
    {
        "id": "smart-ration-card",
        "category": "welfare",
        "name_en": "Smart Family Ration Card",
        "name_ta": "ஸ்மார்ட் குடும்ப அட்டை (ரேஷன் கார்டு)",
        "desc_en": "Primary family entitlement card for subsidized food commodities, welfare schemes, and civic identity.",
        "desc_ta": "அத்தியாவசிய உணவுப் பொருட்கள் மற்றும் அரசு நலத்திட்டங்களுக்கான ஸ்மார்ட் குடும்ப அட்டை.",
        "issuing_authority_en": "Civil Supplies & Consumer Protection Dept",
        "issuing_authority_ta": "உணவுப் பொருள் வழங்கல் மற்றும் நுகர்வோர் பாதுகாப்புத் துறை",
        "standard_fee": "₹20 - ₹30 for PVC Card Printing",
        "processing_days": "15 - 30 Working Days",
        "icon": "shopping-bag",
        "official_portal": "https://www.tnpds.gov.in/",
        "documents": [
            {
                "id": "doc-src-1",
                "name_en": "Aadhaar Cards of All Family Members",
                "name_ta": "அனைத்து குடும்ப உறுப்பினர்களின் ஆதார் அட்டைகள்",
                "category": "primary_proof",
                "reason_en": "Mandatory biometric linkage to prevent duplicate ration cards.",
                "reason_ta": "போலி ரேஷன் அட்டைகளைத் தடுக்க கட்டாய பயோமெட்ரிக் இணைப்பு.",
                "format": "photocopy_self_attested",
                "format_label_en": "Self-Attested Copies of All Members",
                "format_label_ta": "அனைத்து உறுப்பினர்களின் நகல்கள்",
                "note_en": "Head of family is typically the eldest woman (Kalaignar Magalir Urimai scheme compatible).",
                "note_ta": "குடும்பத்தின் மூத்த பெண்மணி குடும்பத் தலைவராக பதிவு செய்யப்பட வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-src-2",
                "name_en": "Current Address Proof (Rental Agreement / EB Bill / Gas Connection)",
                "name_ta": "நடப்பு முகவரி சான்று (வாடகை ஒப்பந்தம் / EB பில் / எரிவாயு இணைப்பு)",
                "category": "address_proof",
                "reason_en": "Assigns neighborhood Fair Price Shop (Ration Kadai).",
                "reason_ta": "உள்ளூர் நியாயவிலைக் கடையை ஒதுக்க முகவரி சான்று அவசியம்.",
                "format": "photocopy",
                "format_label_en": "Recent Bill / Stamped Agreement",
                "format_label_ta": "சமீபத்திய ரசீது / ஒப்பந்தம்",
                "note_en": "Gas consumer book number must be mentioned if household has LPG cylinders.",
                "note_ta": "எரிவாயு இணைப்பு இருப்பின் நுகர்வோர் எண் குறிப்பிடப்பட வேண்டும்.",
                "essential": True,
            },
            {
                "id": "doc-src-3",
                "name_en": "Name Deletion Certificate (Surrender / Nil Slip from Parent Card)",
                "name_ta": "பெயர் நீக்கல் சான்றிதழ் (முந்தைய குடும்ப அட்டையிலிருந்து நீக்கிய ரசீது)",
                "category": "supporting_proof",
                "reason_en": "Proves newly married applicants have removed their names from parents' cards.",
                "reason_ta": "திருமணமானவர்கள் பெற்றோர் அட்டையிலிருந்து பெயரை நீக்கியதற்கான சான்று.",
                "format": "original_and_copy",
                "format_label_en": "Online TNPDS Deletion Slip",
                "format_label_ta": "இணையதள பெயர் நீக்கல் ரசீது",
                "note_en": "Can be generated in 2 minutes on tnpds.gov.in portal.",
                "note_ta": "tnpds.gov.in தளத்தில் எளிதாக பெறலாம்.",
                "essential": False,
                "conditional": "Mandatory if married and splitting from parent card"
            }
        ]
    },
    {
        "id": "death-certificate",
        "category": "certificates",
        "name_en": "Death Certificate",
        "name_ta": "இறப்புச் சான்றிதழ்",
        "desc_en": "Official record of a person's death issued by Corporation, Municipality, or Village Panchayat.",
        "desc_ta": "மாநகராட்சி, நகராட்சி அல்லது கிராம பஞ்சாயத்தால் வழங்கப்படும் அதிகாரப்பூர்வ இறப்பு பதிவு ஆவணம்.",
        "issuing_authority_en": "Corporation / Municipality / Revenue Dept",
        "issuing_authority_ta": "மாநகராட்சி / நகராட்சி / வருவாய்த்துறை",
        "standard_fee": "₹60 (e-Seva charge)",
        "processing_days": "7 - 15 Working Days",
        "icon": "file-text",
        "official_portal": "https://crstn.org/birth_death_tn/",
        "documents": [
            {
                "id": "doc-dc-1",
                "name_en": "Hospital Death Summary / Burial Ground Receipt",
                "name_ta": "மருத்துவமனை இறப்பு அறிக்கை / மயான ரசீது",
                "category": "primary_proof",
                "reason_en": "Proves exact date, cause, and place of death.",
                "reason_ta": "இறந்த தேதி, இடம் மற்றும் காரணத்தை நிரூபிக்கிறது.",
                "format": "original_and_copy",
                "format_label_en": "Original + 1 Copy",
                "format_label_ta": "அசல் + 1 நகல்",
                "note_en": "Cremation/burial receipt signed by graveyard caretaker with burial serial number.",
                "note_ta": "மயான பராமரிப்பாளர் முத்திரை மற்றும் கையொப்பத்துடன்.",
                "essential": True,
            },
            {
                "id": "doc-dc-2",
                "name_en": "Aadhaar Card of Deceased",
                "name_ta": "மறைந்தவரின் ஆதார் அட்டை",
                "category": "identity_proof",
                "reason_en": "Identity and demographic details of the deceased.",
                "reason_ta": "மறைந்தவரின் பெயர் மற்றும் முகவரி சரிபார்ப்பிற்கு.",
                "format": "photocopy",
                "format_label_en": "1 Photocopy",
                "format_label_ta": "1 நகல்",
                "note_en": "Carry original for verification if available.",
                "note_ta": "அசல் இருப்பின் சரிபார்க்க எடுத்துச் செல்லவும்.",
                "essential": True,
            }
        ]
    }
]

def get_all_services():
    """Return all services list."""
    return SERVICES_DATA

def get_service_by_id(service_id: str):
    """Retrieve service by ID."""
    for s in SERVICES_DATA:
        if s["id"] == service_id:
            return s
    return None

def search_services(query: str):
    """Search services by keyword across english and tamil names and description."""
    q = query.lower().strip()
    results = []
    for s in SERVICES_DATA:
        if (
            q in s["id"].lower()
            or q in s["name_en"].lower()
            or q in s["name_ta"].lower()
            or q in s["desc_en"].lower()
            or q in s["desc_ta"].lower()
            or q in s["category"].lower()
        ):
            results.append(s)
    return results
